parameters:
    oxid.database_installer.class: Ellis\Oxid\Bundle\FrameworkBundle\DatabaseInstaller
    oxid.bootstrapper.class: Ellis\Oxid\Bundle\FrameworkBundle\Bootstrapper\Bootstrapper
    oxid.oxid_factory.class: Ellis\Oxid\Bundle\FrameworkBundle\OxidFactory

services:
    oxid.database_installer.connection:
        public: false
        class: mysqli
        arguments: ['%oxid.database.host%', '%oxid.database.user%', '%oxid.database.password%']

    oxid.database_installer:
        class: '%oxid.database_installer.class%'
        arguments:
            - '%oxid.database.host%'
            - '%oxid.database.name%'
            - '%oxid.database.user%'
            - '%oxid.database.password%'
            - '@file_locator'
            - '@oxid.database_installer.connection'

    oxid.bootstrapper:
        class: '%oxid.bootstrapper.class%'
        arguments: ['%kernel.root_dir%/../web']

    oxid.oxid_aware:
        abstract: true
        calls:
            - [setOxidBootstrapper, ['@oxid.bootstrapper']]
            - [bootstrapOxid, []]

    oxid.oxid_factory:
        class: '%oxid.oxid_factory.class%'
        parent: oxid.oxid_aware

    oxid.database_metadata_handler:
        class: oxDbMetaDataHandler
        factory: ['@oxid.oxid_factory', getFromRegistry]
        arguments: ['oxDbMetaDataHandler']
