parameters:
    event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    filesystem.class: Symfony\Component\Filesystem\Filesystem

services:
    event_dispatcher:
        class: '%event_dispatcher.class%'
        arguments: ['@service_container']

    service_container:
        synthetic: true

    filesystem:
        class: '%filesystem.class%'
