parameters:
    event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    cache_clearer.class: Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer
    filesystem.class: Symfony\Component\Filesystem\Filesystem
    file_locator.class: Symfony\Component\HttpKernel\Config\FileLocator

services:
    event_dispatcher:
        class: '%event_dispatcher.class%'
        arguments: ['@service_container']

    cache_clearer:
        class: '%cache_clearer.class%'
        arguments:
            - []

    service_container:
        synthetic: true

    kernel:
        synthetic: true

    filesystem:
        class: '%filesystem.class%'

    file_locator:
        class: '%file_locator.class%'
        arguments: ['@kernel', '%kernel.root_dir%/Resources']
